# Generated by Django 4.2.7 on 2024-01-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='assest/'),
        ),
    ]
