# Generated by Django 4.2.7 on 2024-01-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
