# Generated by Django 4.2.7 on 2024-01-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
